name: project-check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          ["3.10"]
    steps:
      - uses: actions/checkout@v2

      - name: Install python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version:
            ${{ matrix.python-version }}
          architecture: x64

      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.1.12
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test

      - name: Upload code coverage
        uses: paambaati/codeclimate-action@v2.4.4
        env:
            CC_TEST_REPORTER_ID: 8fed69dab2e1a795ae2c302eeac299f1f38cea14f3d181de4ba6187a7ae4ae12
        with:
            coverageCommand: make coverage